"""add asset officer role asset tag location warranty movement table

Revision ID: 3975335792d3
Revises: e86e47e2dbf2
Create Date: 2026-07-19 18:52:19.564811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3975335792d3'
down_revision = 'e86e47e2dbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected'),
               type_=sa.Enum('pending', 'approved', 'rejected', 'processed'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'processed'),
               type_=mysql.ENUM('pending', 'approved', 'rejected'),
               existing_nullable=True)

    # ### end Alembic commands ###
