"""fix cascade deletes on user foreign keys

Revision ID: 5d5b54ecee1b
Revises: 3975335792d3
Create Date: 2026-07-19 23:20:20.103686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d5b54ecee1b'
down_revision = '3975335792d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_requests', schema=None) as batch_op:
        batch_op.alter_column('requested_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('allocation_requests_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['requested_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('allocations_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.alter_column('moved_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('asset_movements_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['moved_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('assets_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['last_verified_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('audit_logs_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_ibfk_1'), 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_logs_ibfk_1'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assets_ibfk_3'), 'users', ['last_verified_by'], ['id'])

    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('asset_movements_ibfk_3'), 'users', ['moved_by'], ['id'])
        batch_op.alter_column('moved_by',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('allocations_ibfk_3'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('allocation_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('allocation_requests_ibfk_2'), 'users', ['requested_by'], ['id'])
        batch_op.alter_column('requested_by',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
