"""add technician fields to category

Revision ID: 6b446c0dcbc2
Revises: a6c5f0156bec
Create Date: 2026-07-02 00:13:20.869956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b446c0dcbc2'
down_revision = 'a6c5f0156bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('technician_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('technician_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('technician_phone')
        batch_op.drop_column('technician_email')
        batch_op.drop_column('technician_name')

    # ### end Alembic commands ###
