"""add staff permissions borrow dates audit log

Revision ID: 950e345752b0
Revises: 7df247f97552
Create Date: 2026-07-05 01:36:32.885912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950e345752b0'
down_revision = '7df247f97552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.Enum('department', 'staff'), nullable=True))
        batch_op.add_column(sa.Column('borrow_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('expected_return_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('borrow_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrow_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('expected_return_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'returned', 'overdue', 'pending_approval'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('expected_return_date')
        batch_op.drop_column('borrow_start_date')

    with op.batch_alter_table('allocation_requests', schema=None) as batch_op:
        batch_op.drop_column('borrow_days')
        batch_op.drop_column('expected_return_date')
        batch_op.drop_column('borrow_start_date')
        batch_op.drop_column('request_type')

    # ### end Alembic commands ###
