"""add asset officer role asset tag location warranty movement

Revision ID: e86e47e2dbf2
Revises: 950e345752b0
Create Date: 2026-07-19 15:00:09.154076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e86e47e2dbf2'
down_revision = '950e345752b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('from_department_id', sa.Integer(), nullable=True),
    sa.Column('to_department_id', sa.Integer(), nullable=False),
    sa.Column('moved_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('moved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['moved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_tag', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('warranty_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_verified_by', sa.Integer(), nullable=True))
        batch_op.alter_column('condition',
               existing_type=mysql.ENUM('new', 'good', 'fair', 'poor'),
               type_=sa.Enum('new', 'good', 'fair', 'poor', 'damaged', 'lost', 'disposed'),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('available', 'allocated', 'under_maintenance', 'disposed'),
               type_=sa.Enum('available', 'allocated', 'under_maintenance', 'disposed', 'lost', 'damaged'),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['asset_tag'])
        batch_op.create_foreign_key(None, 'users', ['last_verified_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'department_head', 'staff'),
               type_=sa.Enum('admin', 'department_head', 'staff', 'asset_officer'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'department_head', 'staff', 'asset_officer'),
               type_=mysql.ENUM('admin', 'department_head', 'staff'),
               existing_nullable=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.Enum('available', 'allocated', 'under_maintenance', 'disposed', 'lost', 'damaged'),
               type_=mysql.ENUM('available', 'allocated', 'under_maintenance', 'disposed'),
               existing_nullable=True)
        batch_op.alter_column('condition',
               existing_type=sa.Enum('new', 'good', 'fair', 'poor', 'damaged', 'lost', 'disposed'),
               type_=mysql.ENUM('new', 'good', 'fair', 'poor'),
               existing_nullable=True)
        batch_op.drop_column('last_verified_by')
        batch_op.drop_column('last_verified_at')
        batch_op.drop_column('warranty_expiry')
        batch_op.drop_column('location')
        batch_op.drop_column('asset_tag')

    op.drop_table('asset_movements')
    # ### end Alembic commands ###
